### ISSUE TITLE
R Studio crashes reading file

### ISSUE THREAD

**Issue by PKHND** [nacnudus/tidyxl#71]
I keep crashing R Studio when trying to read the attached xlsx file. Any thoughts or workarounds? Thanks.
[reporteinstitucion dsh_637564984151768951.xlsx](https://github.com/nacnudus/tidyxl/files/6479718/reporteinstitucion.dsh_637564984151768951.xlsx)

**Comment by nacnudus** [comment]
Thank you for taking the trouble to report this.  I can reproduce the crash, but I don't know why it does yet.

I opened it in LibreOffice Calc, saved a new copy of it, and that copy opens in tidyxl.  Perhaps that would work for you (or use Excel, or Google Sheets, or whatever other spreadsheet software is available to you).

**Comment by PKHND** [comment]
Thanks. I did open the file in Sheets and then exported it to Excel. It worked. 

The problem with the approach is the amount of files to open and save. If you find a solution I would appreciate your input.

**Comment by nacnudus** [comment]
I will keep trying to find the cause of the error.

If you can use libreoffice from the command line, then it's possible to process the files as a batch.  See for example https://www.libreofficehelp.com/batch-convert-writer-documents-pdf-libreoffice/.

**Comment by PKHND** [comment]
Excellent, I'll try your recomendation.

**Comment by nacnudus** [comment]
I think this is now fixed.  Please reopen this issue if not.

**Comment by e-mcbride** [comment]
Hi @nacnudus I am still encountering this issue using tidyxl to import an .xlsx file downloaded from SurveyMonkey. I have tidyxl version 1.0.7 installed. Your fix did work though: once I opened the file in Excel and saved a new copy, it imported successfully.

**Comment by nacnudus** [comment]
@e-mcbride sorry that you're having this problem, thank you for reporting it.  Are you able to install the latest version 1.0.7.9000 from GitHub by doing, for example, `remotes::install_github("nacnudus/tidyxl")`?  If that fixes the problem, then I will publish this version to CRAN.

**Comment by e-mcbride** [comment]
@nacnudus unfortunately that didn't work :/ Let me know if there is anything else I can do to test this!

**Comment by nacnudus** [comment]
@e-mcbride Please can you provide an example file that causes the error?

**Comment by e-mcbride** [comment]
@nacnudus Thank you so much for looking into it! Here you go: https://ucsb.box.com/s/3h6dg2hsmgx08laseag2ml88v1oqfg0t

**Comment by nacnudus** [comment]
@e-mcbride Thanks for providing the file.  The cause is different from the one in this issue, so I have created a new issue #73 to track it.  Sorry it has taken me so long to address this.
